using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NavPoint : MonoBehaviour
{
    public Vector3 position => gameObject.transform.position;
    public float FlagDistance { get; private set; }
    [System.NonSerialized] public float DeathAttr;
    [System.NonSerialized] public List<Vector3> EnemiesSeen;
    //Here other attributes;

    [SerializeField]
    public int PointId;

    private void Awake()
    {
        //DO NOT DELETE
    }

    private void Start()
    {
        FlagDistance = (GameObject.FindGameObjectWithTag("Flag").transform.position - position).magnitude;
        EnemiesSeen = new List<Vector3>();
        DeathAttr = 0;
    }
}
