using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NavPoint : MonoBehaviour
{
    public Vector3 position => gameObject.transform.position;
    public float FlagDistance { get; private set; }

    [HideInInspector]
    public int? PointId;
    public float DeathAttr = 0;
    public List<Vector3> EnemiesSeen = new List<Vector3>();
    //Here other attributes;

    private void Start()
    {
        FlagDistance = (GameObject.FindGameObjectWithTag("Flag").transform.position - position).magnitude;               
    }
}
